Feature/ez 45 get data
ezyquant/ezyquant pull request #17
Opened 2022-05-23 08:17 UTC by armykongtap

EZ-45 [SSC] get_data

2022-05-24 12:42 UTC, eakkatachFintech requested changes

2022-05-24 12:42 UTC, eakkatachFintech commented on ezyquant/creator.py
> +    def get_data(
เปลี่ยน default 

field,
timeframe,
value_by = 'stock',
method = 'constant',
period = 1,
shift = 0,

2022-05-24 12:42 UTC, eakkatachFintech commented on ezyquant/creator.py
> +    def get_data(
ไม่แน่ใจว่าได้ check ไหมว่า method = 'constant' แล้ว period ต้องเป็น period 1 เท่านั้น

2022-05-25 04:05 UTC, armykongtap commented on ezyquant/creator.py
> +    def get_data(
เพิ่ม if เพื่อเช็คครับ

2022-05-25 04:20 UTC, eakkatachFintech approved these changes

2022-05-25 04:46 UTC, merged